### ISSUE TITLE
OSError: File my-model.ckpt.meta does not exist.

### ISSUE THREAD

**Issue by chitransh1998** [tpvt99/character-recognition-cnn#1]
Hii,
I tried to run the test.py  and I am getting the following error.
I am unable to understand which file it wants.

Traceback (most recent call last):
  File "test.py", line 114, in <module>
    new_saver = tf.train.import_meta_graph('my-model.ckpt.meta')
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1947, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 632, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File my-model.ckpt.meta does not exist.

![image](https://user-images.githubusercontent.com/37555185/41410527-64bed45c-6ff7-11e8-8305-0b69d205cb76.png)

Please help,
I need it urgently for a project
Thankyou

**Comment by tpvt99** [comment]
oh, you need to train so as to recognize it. run the training file

**Comment by tpvt99** [comment]
that is the file to save the model after training. Training and you will
get that file. Thanks.

**Comment by tpvt99** [comment]
hey, have you found the solution yet?
